import "./globals.css";
import type { Metadata } from "next";
import ThemeRegistry from "../../theme/ThemeRegistry";
import ReactQueryProvider from "@/provider/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <ReactQueryProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
